[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.86"
axum = "0.8.1"
chrono = "0.4.38"
reqwest = { version = "0.12.7", features = ["json"] }
serde = { version = "1.0.209", features = ["derive"] }
tokio = { workspace = true }
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
dotenv = "0.15.0"
